# Generated by Django 2.2 on 2021-06-13 12:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='resident',
        ),
        migrations.AddField(
            model_name='resident',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='app.Community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Please enter at least 2 charactors')]),
        ),
        migrations.AlterField(
            model_name='community',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8, 'Please enter at least 8 charactors')]),
        ),
        migrations.AlterField(
            model_name='resident',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Please enter at least 2 charactors')]),
        ),
    ]
