# Generated by Django 2.2 on 2021-06-24 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20210619_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_like',
            field=models.ManyToManyField(null=True, related_name='video_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
