# Generated by Django 2.2 on 2021-06-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210624_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user_like',
        ),
        migrations.AddField(
            model_name='video',
            name='resident_like',
            field=models.ManyToManyField(related_name='video_like', to='app.Resident'),
        ),
    ]
